version: '3.8'

services:
  dockertrap:
    build:
      context: .
      dockerfile: build.Dockerfile
    ports:
      - ${APP__PORT}:${APP__PORT}
    environment:
      PYTHONPATH: /app/src
    extra_hosts:
      - host.docker.internal:host-gateway
